FROM ghcr.io/cirruslabs/flutter:latest AS build
USER root
WORKDIR /app
COPY . .
RUN flutter pub get
RUN flutter build web --release
FROM cgr.dev/chainguard/caddy:latest
COPY --from=build /app/build/web /usr/share/caddy
EXPOSE 80
CMD ["file-server", "--root", "/usr/share/caddy"]
