services:
  frontend:
    image: superscalecloud/dragonscale-frontend
    build: 
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "80:80"
    restart: unless-stopped

  backend:
    image: superscalecloud/dragonscale-backend
    build:
      context: ./backend
      dockerfile: dockerfile
    restart: unless-stopped