services:
  frontend:
    container_name: "frontend"
    image: superscalecloud/dragonscale-frontend
    build: 
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "80:80"
    restart: unless-stopped

  backend:
    container_name: "backend"
    image: superscalecloud/dragonscale-backend
    build:
      context: ./backend
      dockerfile: dockerfile
    restart: unless-stopped
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock