FROM cgr.dev/chainguard/go:latest-dev AS builder
WORKDIR /app
COPY go.mod go.sum ./
COPY . .
RUN go build -o docker ./cmd/dragonscale
FROM cgr.dev/chainguard/go:latest-dev
COPY --from=builder /app/docker /usr/bin/docker
EXPOSE 8080
USER root
ENTRYPOINT [ "/usr/bin/docker" ]