FROM cgr.dev/chainguard/go:latest-dev AS builder
WORKDIR /app
COPY go.mod go.sum./
COPY . .
RUN go build -o docker .
FROM cgr.dev/chainguard/static
COPY --from=builder /app/docker /usr/bin/docker
EXPOSE 8080
CMD ["/usr/bin/docker"]
